all:
	$(MAKE) -C ./0-problem-formulation/
	$(MAKE) -C ./1-threads/
	$(MAKE) -C ./2-cuda/
	@echo
	@echo Built all subdirectories.
	@echo

clean:
	$(MAKE) -C ./0-problem-formulation/ clean
	$(MAKE) -C ./1-threads/ clean
	$(MAKE) -C ./2-cuda/ clean
	@echo
	@echo Cleaned all subdirectories.
	@echo
